#!/usr/bin/env bash
jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager --minimize=False
jupyter lab build --minimize=False